### ISSUE TITLE
[Feat] navigation path 연결 및 구현

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#13]
## Description

추후 원활한 navigation 관리를 위해 연결하면서 path 관리 하도록 구현

## TODO

- [ ] NavigationStack(path: ) 연결
- [ ] 임의의 View 파서 연결
- [ ] 하면서 HomeView에 뷰빌더로 내리기
