### ISSUE TITLE
[Feat] CakeColorView UI 구현

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#15]
## Description

CakeColorView(케이크 색상 선택) UI 그리기

## TODO

- [x] NavigatioinBackButton Custom 진행
- [x] 프로그래스 바 (공통적으로 사용될 예정으로 Component로 따로 빼기)
- [x] 안내 문구 작성 (공통적으로 사용될 예정으로 Component로 따로 빼기 - 텍스트만 바뀔 수 있도록)
- [x] AR 들어올 자리 확보
- [x] ColorPicker 구현 (공통적으로 사용될 예정으로 Component로 따로 빼기)
- [x] 다음 버튼 구현 (공통적으로 사용될 예정으로 Component로 따로 빼기)
