### ISSUE TITLE
[Feat] CakeImageView UI 구현

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#28]
## Description

CakeImageView UI 구현

## TODO

- [x] 안내 문구 추가
- [x] SKIP 버튼추가 (기능 미구현으로)
- [x] 다음 버튼 추가
- [ ] 이미지 추가하는 carousel 구현
- [ ] 텍스트 필드 구현 (사진 추가하면 나타나는 로직 기능은 미구현으로 & 키보드 올라오면 화면도 같이 올라가도록 해야함)

## ScreenShot 

<img width="279" alt="image" src="https://github.com/user-attachments/assets/21300378-38c9-42d8-9be3-dc425e0a040d">
<img width="266" alt="image" src="https://github.com/user-attachments/assets/1586b648-1966-4d74-8633-107263a82161">
<img width="267" alt="image" src="https://github.com/user-attachments/assets/d831ff3b-fee5-4c17-9281-d20d06146059">
