### ISSUE TITLE
[Feat] CakeDecorationView UI 구현

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#30]
## Description

CakeDecorationView UI 구현

## TODO

- [x] customNavigationBackButton 구현
- [x] toolBar 자리에 '완료' 버튼 구현 (기능 연결 제외)
- [x] 프로그래스바 
- [x] 안내 문구
- [x] 도라미 3D 자리 영역 표시
- [x] 데코 시 필요한 버튼 3개 구현 (기능 연결은 도라미)
- [ ] 앞에서 저장한 이미지 나타나는 LazyHStack 구현 (데이터 연결 제외)

## ScreenShot 

<img width="245" alt="image" src="https://github.com/user-attachments/assets/c2cee651-2d42-4c2b-82da-47f243bdf5ec">
