### ISSUE TITLE
[Feat] CakeLetteringView UI 구현

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#32]
## Description

CakeLetteringView UI 구현
## TODO

- [ ] 프로그래스바
- [ ] 안내 문구
- [ ] 임시 케이크 사진 설정 + 도라미 작업 영역 설정
- [ ] 임시 케이크 위에 textEditor로 적은 문구 반영
- [ ] colorPicker 추가
- [ ] textEditor 추가
- [ ] 다음 버튼 추가

## ScreenShot 

<img width="279" alt="image" src="https://github.com/user-attachments/assets/846d7220-2628-4506-8da8-8a19d120fb5d">
