### ISSUE TITLE
[Chore] 자잘한 디자인 수정건 

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#42]
## Description

디자인 변경 건 수정
## TODO

- [x] 프로그래스바 5단계로 수정
- [x] 케이크 꾸미기 단계에서 완료 -> 다음 수정
- [x] 케이크 꾸미기 단계에서 사진 갯수 5개 -> 6개로 수정
