### ISSUE TITLE
[Feat] CakeImageView 기능 구현 (누끼 우선 제외)

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#59]
## Description

CakeImageView 기능 구현
## TODO

- [x] 사진추가 누르면 앨범 뜨도록 구현
- [x] 사진 선택하면 화면에 뜨도록 구현
- [x] 사진 추가하기 전에 textfield 비활성화 구현
- [x] 각 index에 맞게 배열로 저장되도록 구현
- [x] SKIP 구현

## ScreenShot 

<img width="255" alt="image" src="https://github.com/user-attachments/assets/24b7a281-92c6-4268-82e3-ce9b5c004aba">
<img width="256" alt="image" src="https://github.com/user-attachments/assets/93337a8d-d533-462f-97c5-5eb797e0c133">
