### ISSUE TITLE
[Feat] CakeyHomeView UI 구현

### ISSUE THREAD

**Issue by onesunny2** [onesunny2/Sgrrl_Cakey#6]
## Description

홈 화면 UI 그리기

## TODO

- [x] 케이크 이미지 등록 및 얹기
- [x] 버튼 2개 action 비워두고 UI 그리기
- [ ] 주문서 불러오기는 임의의 EmptyView로 두기

## ScreenShot 

![image](https://github.com/user-attachments/assets/b55e942b-57fd-4378-8b94-68eb358b2abe)
