### ISSUE TITLE
[Feat] CakeDecoration3D 디테일 수정

### ISSUE THREAD

**Issue by dorachoii** [onesunny2/Sgrrl_Cakey#70]
## Description
- Cake Decoration 디테일 수정
- Cake Decoration 온보딩 추가
- Cake Color, Decoration 모델 연결

## TODO
- [ ] CakeDecorationView: 카메라 슬라이더에 따른 모델 크기 세부 조정
- [ ] CakeDecorationView: 보기 모드 - 모델 확대 축소 범위 조정
- [ ] CakeDecorationView: 편집 모드 - clampPosition 함수 세부 범위 조정
- [ ] CakeDecorationView: 온보딩 추가
- [ ] CakeDecorationView: decoImageList, selected Color 모델과 연동
